### ISSUE TITLE
v2p1 context file

### ISSUE THREAD

**Issue by ahripak** [IMSGlobal/openbadges-specification#227]
Merge obc context properties into the ob context file and name it v2p1

**Comment by ottonomy** [comment]
I noted these things on a cursory initial inspection of the current generated file, for discussion:

- The "@context" property in the 2.1 context is messed up, this makes the context file invalid JSON-LD. This property should just be removed.
- Term names from 2.0 have changed IRIs for terms of the same short name, which is not recommended.
- The term names are defined here relative to a 2.1-specific base URL, instead of a common terms vocabulary that doesn't change across versions (even major versions). This means there would be breaking changes to term names for every minor version unnecessarily if we carried the practice forward. 
- 2.0 terms necessary to describe assertion objects are not included in 2.1 contexts, rendering assertions sent over API meaningless in the JSON-LD sense unless they include the 2.0 context at the top of each individual document, which *is* our recommendation for implementers and how the examples appear in the spec document, though it slightly increases processing time. We should try to avoid using the same property names for different IRIs in 2.0 context vs 2.1 context though. It's fine to use the same names in these two versions, but when that occurs, the IRI should match, for cleanliness. Term IRIs in use should in 2.0 should probably be preserved unless there is an overriding justification to make breaking changes.

Though from discussion today it looked like we would likely go with a hand-crafted context file, the advances in the automatic generation are great to see, and we should make sure that we move toward a good consistent strategy for using JSON-LD contexts and terms across specs. Thanks for the good work @andyfmiller and @ahripak.

**Comment by ottonomy** [comment]
@jbohrer why is this ticket closed as well as the duplicate #228? Has a context file been authored that addresses the above points?

**Comment by jbohrer** [comment]
Yes, that's correct.
