### ISSUE TITLE
Consider PKCE Requirement

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges-specification#252]
[PKCE](https://tools.ietf.org/html/rfc7636) is listed as required in the OB 2.1 Badge Connect specification. It is a technique to mitigate potential attacks against public OAuth clients (i.e. clients that do not have the ability to keep confidential a client secret). Badge Connect does not include any user stories that would allow the use of public clients. All Badge Connect clients must be "confidential"; they must have a client secret.

PKCE MAY be used with confidential clients to increase security. This comes with increased implementation costs. As we begin our implementation of the spec, we are finding that the libraries we rely on for OAuth2 do not yet support PKCE, so we would incur some pretty significant extra cost if this remained required as currently listed.

We talked about this in Q2 and that the spec is primarily designed for public clients. I wasn't aware of a meeting where this was decided to be required, though I have missed a couple meetings in the last 4 months. @amiller-ims @ahripak @justinpitcher could you speak to how PKCE got into the required section and to whether there is an option to remove it given that there are not any public clients present in our use cases that are susceptible to the attack that PKCE is designed to prevent?

**Comment by amiller-ims** [comment]
If I recall correctly, PKCE was made a requirement in the IMS Security Framework after the IETF released their [Best Current Practice](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-11#section-2.1.1) document on 28 December 2018.
> Note: although PKCE so far was recommended as a mechanism to protect native apps, this advice applies to all kinds of OAuth clients, including web applications.
PKCE was made a requirement in the OB 2.1 Badge Connect specification because the requirement applies to all IMS specifications that use the Authorization Code flow.

Dereck and I raised the issue internally on 11/22 and I sent out an email poll to gather more information.

**Comment by jbohrer** [comment]
Closing due to the issue moving to [IMS Security Framework #76](https://github.com/IMSGlobal/security-framework/issues/76)
