### ISSUE TITLE
Referencing OB JSON-LD context files

### ISSUE THREAD

**Issue by amiller-ims** [IMSGlobal/openbadges-specification#253]
The UML model for OB 2.1 only models the API. The generated JSON-LD context file only defines the terms that are used by the API. "Assertion" and "Profile" appear in both the 2.0 and 2.1 context files. In 2.1 "Assertion" and "Profile" are modeled as generic objects with no specific properties.

A suggested best practice for implementers is to reference both the 2.0 and 2.1 context files. Order is important. Reference 2.0 last so that the 2.0 definition of "Assertion" and "Profile" is used. For example,
```
"@context": [
    "https://purl.imsglobal.org/spec/ob/v2p1/context/ob_v2p1.jsonld",
    "https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/v2/context.json"
]
```

**Comment by ottonomy** [comment]
@amiller-ims I don't see `Assertion` referenced in the 2.1 context that you linked, is it present in an updated version that is not yet published to that URL?

**Comment by amiller-ims** [comment]
Sort of.

`Assertion` is in the model as described above, but the generated context file defines the term `dtAssertion` instead of `Assertion`. I've asked Colin to fix that.

```
        "obc" : "https://www.imsglobal.org/spec/ob/v2p1#",
        "xsd" : "http://www.w3.org/2001/XMLSchema#",

        "dtAssertion" : "obc:dtAssertion",
        "dtAssertionsResponse" : "obc:dtAssertionsResponse",
        "dtBadgeConnectAPI" : "obc:dtBadgeConnectAPI",
        "dtProfile" : "obc:dtProfile",
        "dtProfileResponse" : "obc:dtProfileResponse",
        "dtStatus" : "obc:dtStatus",
        "dtStatusResponse" : "obc:dtStatusResponse",
```

**Comment by ottonomy** [comment]
Interesting, indeed those terms dtAssertion and dtProfile do not yet appear in the [published context file](https://purl.imsglobal.org/spec/ob/v2p1/context/ob_v2p1.jsonld) on the purl server. Yes if that fix is made, there would be an overlapping definition for Assertion that places that term at different IRIs, and I can't see why that would be a good thing to do, even if paired with recommendations or requirements that implementers fix that problem themselves by placing contexts in the appropriate order or override specificity by nesting. 

Just another note to remind you that I'm concerned that the vocabulary namespace "obc" is versioned. We have had discussions in the group that this is not the appropriate way to use a vocabulary in JSON-LD. Is it also possible to place these terms within a namespace for Open Badges that does not change across Open Badges Specification minor and major versions? We already have such a namespace `https://w3id.org/openbadges#` that could resolve in a redirect to whatever the current most appropriate vocabulary document is at the time so that it could continue to serve this purpose. Certainly in a point release, we can't change the IRIs of terms defined in 2.0, which is why you propose this override strategy, but I hope we can look forward to the future in terms of the IRIs so that they do not change unnecessarily when the meaning of these terms do not change.

Do you recall those discussions in the workgroup?

**Comment by jbohrer** [comment]
IMS staff will confirm that the updated (custom written) context file is indeed published and available.

**Comment by amiller-ims** [comment]
The custom written context file from the [Github repo](https://github.com/IMSGlobal/badge-connect-api/blob/develop/ob_v2p1/schema/jsonld-context/context.json) is available online at: 

https://purl.imsglobal.org/spec/ob/v2p1/context/context.json

IMS will update redirects when the spec is approved and goes final.

**Comment by danblickensderfer** [comment]
Kerri Lemoie suggested that we could reanimate this issue to correct that:   "obi" : "https://purl.imsglobal.org/spec/ob/vocab#",  is broken (URL is 404) in these three places in OB https://github.com/IMSGlobal/openbadges-specification 

ob_v3p0/context.json
docs/context.json
ob_v2p1/schema/jsonld-context/ob_v2p1.jsonld

**Comment by amiller-ims** [comment]
@danblickensderfer

I don't think this issue covered every covered this problem. I think you should open a new issue.

As an aside, it is not "broken". The syntax `"obi" : "https://purl.imsglobal.org/spec/ob/vocab#"` just defines "obi" as a prefix. The part on the right is only required to be an IRI. The fact that it appears to be a URL does not make it "broken".

It would be nice if the IRI actually did point to an HTML page that described the terms. So maybe a new issue could be created to "Create an HTML page at "https://purl.imsglobal.org/spec/ob/vocab".

Unfortunately, none of our tooling will generate that page. Writing the code to generate that page might fit within the OB 3.0 timeframe, but no guarantee. Alternatively some individual could volunteer to create and maintain the page.

**Comment by danblickensderfer** [comment]
Closing this as recommended by @amiller-ims; new issue is https://github.com/IMSGlobal/openbadges-specification/issues/329
