### ISSUE TITLE
Create an HTML page at "https://purl.imsglobal.org/spec/ob/vocab"

### ISSUE THREAD

**Issue by danblickensderfer** [IMSGlobal/openbadges-specification#329]
The OB 3.0 (and other) context.json file includes the syntax "obi" : "https://purl.imsglobal.org/spec/ob/vocab#" to define "obi" as a prefix. This is only required to be an IRI. When clicked now, it is not a functioning URL.

This issue can be used to make the IRI point to an HTML page that describes the terms. 

Our automation/tooling will not currently generate this HTML page. A volunteer could create and maintain the HTML page needed or adding code to generate that page might fit within the OB 3.0 timeframe, but no guarantee. 

Other notes:
Kerri Lemoie suggested that we should correct that: "obi" : "https://purl.imsglobal.org/spec/ob/vocab#", is not a functioning URL (URL is 404) in these three places in OB https://github.com/IMSGlobal/openbadges-specification

ob_v3p0/context.json
docs/context.json
ob_v2p1/schema/jsonld-context/ob_v2p1.jsonld

Tasks:

- [ ] Create the vocab file
- [ ] Update "https://w3id.org/openbadges" redirect on w3id.org to redirect to the vocab file

**Comment by amiller-ims** [comment]
In OB 2.1, CLR 1.0, and CASE-LD 1.0; the auto-generation script creates two context files: context.json and context.html. For example: https://purl.imsglobal.org/spec/clr/v1p0/context/clr_v1p0.html.

If the PURL server treats the final path segment as a folder and looks in that folder for a default index.html page, then this would probably work:

- Rename https://purl.imsglobal.org/spec/ob/v3p0/context/context.html to https://purl.imsglobal.org/spec/ob/v3p0/context/index.html
- Change vocab to `"obi": "https://purl.imsglobal.org/spec/ob/v3p0/context#"`

**Comment by amiller-ims** [comment]
The term `obi` expands to "https://w3id.org/openbadges#" since at least [ob1](https://openbadgespec.org/v1/context.json). If a human browses to that URL, they currently see the [OB 2.0 spec](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html). This redirect is managed via w3id.org UI.

Whatever vocab file is used, the URL https://w3id.org/openbadges should be modified to redirect to that file.

**Comment by amiller-ims** [comment]
Options for vocab:

- The html file that is generated by IMS' data modeling tools
- The latest OB spec
- A new vocab file, ideally generated from .lines file

Since all badges regardless of version use the same IRI for `obi`, the vocab file should include a narrative explaining which terms apply to each version of the OB spec.

**Comment by danblickensderfer** [comment]
Single glossary of terms that includes items marked as deprecated - Nate
I’m leaning toward the new vocab file. Two versions in the same file seem confusing to me. - Phil
Options for having two files; could avoid confusion of versioned terms- Dimitri
If we changed the URI for “obi” would it be necessary to rename the term as well (e.g. “obi3”)? - Justin
if we change the underlying IRI for a term, then we have no real way other than magic to assert that the two terms are equivalent. - Viktor/Dmitri
New terms could have new and changed terms only; existing terms unchanged in original URI (2 files) Dmitri

**Comment by danblickensderfer** [comment]
- [ ] We could sketch up one or two ideal vocab files and review by the work group
- [ ] Ideal existing vocab files specs?
- [ ] Create a simple respec file with terms, anchor links, etc. as an example -- Andy will set this up for review by work group (one new term, one old term as reference

**Comment by amiller-ims** [comment]
Prototype in PR #348

**Comment by amiller-ims** [comment]
Closing since PR #348 was merged.
