### ISSUE TITLE
OB 3.0: Person and Organization Identifiers

### ISSUE THREAD

**Issue by amiller-ims** [IMSGlobal/openbadges-specification#336]
In OB20, issuers are identified with a [Profile](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#Profile). "Recipients, endorsers, or other entities may also be represented using this vocabulary." Recipients are identified with an [IdentityObject](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#IdentityObject) which describes a Profile property value that can be used to find the recipient's Profile. For example, the Profile with an email value of person@example.edu.

In OB30/VC11, issuers, holders, and subjects are identified with an `id`.

Migrating from OB20 `issuer` to OB30 `issuer` is easy. The OB20 Profile class is a good match for OB30/VC11 `issuer` and OB30 `creator` partly because the intent is the same, and partly because the Profile class has an `id` property with the same type and meaning as in VC11. The only caveat is that a OB20 Profile class can represent a person or an organization. If in practice OB30 `issuer` and `creator` will always an organization, perhaps the IMS Common Data Model [Organization](https://imsum2.herokuapp.com/browser?id=org.1edtech.common.model#org-1edtech-common-organization-class) is a better choice.

Migrating from OB20 `recipient` to OB30 `credentialSubject` is not as easy. The OB20 IdentityObject class intentionally does not have an `id` property. And subclassing the OB20 Profile class does not obfuscate the recipient's `id` like OB20 does. The IdentityObject is also not a good match for the VP `holder` property for similar reasons (the holder is sometimes the subject).

- [ ] Does OB30 need to obfuscate the subject's `id` like the recipient's `id` is obfuscated in OB20?
  - [ ] If no, should `credentialSubject` be a subclass of Profile which can be a person or an organization, or CDM [Person](https://imsum2.herokuapp.com/browser?id=org.1edtech.common.model#org-1edtech-common-person-class), or something else? Using CDM Person may add better synchronization with systems that use IMS rostering specs.
  - [ ] If yes, can `credentialSubject` be a subclass of IdentityObject, or should `credentialSubject` has a property `recipient` which is an IdentityObject?
- [ ] Does OB30 need to obfuscate the holder's `id` when the holder is the subject?
- [ ] Should `issuer` and `creator` be identified with a Profile that can represent a person or an organization, or more specifically by a CDM Organization? Using CDM Organization may add better synchronization with systems that use IMS rostering specs.

**Comment by kayaelle** [comment]
Great questions. Here are some thoughts:

Re: Organization vs Profile (and Issuer & Creator): We probably shouldn't always assume the creator or issuer are always organizations and continue using [Profile](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#Profile). We'd want the flexibility for use cases such as self-assertion and peer-to-peer badge. 

Re: credentialSubject - this property in VC is analogous to "the claim". In VC terms, the credentialSubject can be about a person but also about a thing. The credentialSubject is a required property of the VC standard and can't be a subclass of another property. The credentialSubject.ID is not a required property but if a VC is to be stored in and presented from a wallet, it is required. That said, many open badges issuers will want to continue to issue to email addresses and we should accommodate both. The credentialsSubject may contain an ID but it may also contain an IdentityObject -- one of these must be present. If a badge contains both a DID and an email address, it provides the verifier with more than one way to verify the subject and the presenter (the holder).

re: obfuscation: the credentialSubject.id (typically a DID) should bot be hashed. I think we should recommend hashing of the email address (I believe this is optional) to protect recipients from spam and cross-correlation of data. We may wish to consider adding more properties about the recipient such as CDM Person but have to keep in mind that the assertion data could be publicly viewable so would want to recommend how to protect that data. Since including the identityObject would be an IMS addition, we may want to reach out to the VC/VC-EDU community for input.

**Comment by amiller-ims** [comment]
> re: obfuscation: the credentialSubject.id (typically a DID) should not be hashed. I think we should recommend hashing of the email address (I believe this is optional) to protect recipients from spam and cross-correlation of data.

Yes, the `identity` property of the [IdentityObject](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#IdentityObject) is the hashed or plaintext value of the recipient's Profile property used to identify the recipient. In OB 2.0, the recipient can be identified by the Profile's [`email`, `telephone`, or `url` properties](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#ProfileIdentifierProperties). In CLR 1.0, the recipient can also be identified by the Profile's `id`, `sourcedId`, or `studentId` properties.

> We may wish to consider adding more properties about the recipient such as CDM Person but have to keep in mind that the assertion data could be publicly viewable so would want to recommend how to protect that data.

This is what I was (poorly) describing in my original post. It seems antithetical to the original reasoning (at least what I imagine the reasoning was) behind OB using an IdentityObject rather than the recipient's Profile to identify the recipient. But perhaps times have changed and there are use cases that require sharing more information about the recipient.

In OB 2.0, there is no way for a verifier to see the recipient's Profile. OB 2.1 added an API endpoint to retrieve the recipient's Profile, but the endpoint requires authorization so the Profile is not publicly viewable.

**Comment by kayaelle** [comment]
Adding a sample of json here to help facilitate discussion.

Can also be found here: https://json.link/UuMdD3fpve.json

`{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/openbadges/v3"
  ],
  "type": [
    "VerifiableCredential",
    "OpenBadge"
  ],
  "id": "https://website-that-supports-or-displays-the-badge.html",
  "issuer": {
    "id": "did:example:issuer",
    "name": "An Example Issuer",
    "image": "https://example.org/logo.png",
    "url": "https://example.org",
    "email": "contact@example.org"
  },
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:learner",
    "recipient": {
      "type": "email",
      "hashed": true,
      "salt": "deadsea",
      "identity": "sha256$c7ef86405ba71b85acd8e2e95166c4b111448089f2e1599f42fe1bba46e865c5"
    },
    "achievement": {
      "id": "https://example.org/achievements/123",
      "type": "Achievement",
      "achievementType": "Certificate",
      "name": "Robotic Drones Analysis",
      "description": "Learn to analyze and present the different types of robotic drones",
      "image": "https://example.org/drone-image.png",
      "creator": "did:example:issuer",
      "criteria": "https://example.org/robotics-drone-analysis.html",
      "tags": [
        "robots",
        "not birds"
      ],
      "alignment": [
        {
          "targetName": "CCSS.ELA-Literacy.RST.11-12.3",
          "targetUrl": "http://www.corestandards.org/ELA-Literacy/RST/11-12/3",
          "targetDescription": "Follow precisely a complex multistep procedure when carrying out experiments, taking measurements, or performing technical tasks; analyze the specific results based on explanations in the text.",
          "targetCode": "CCSS.ELA-Literacy.RST.11-12.3"
        }
      ],
      "resultDescription": [
        {
          "id": "urn:uuid:da72e42e-9f38-4c42-83ac-33f6cb9bb3b1",
          "name": "Mastery",
          "resultType": "PerformanceLevel",
          "rubricCriterionLevels": [
            {
              "id": "urn:uuid:24df3f14-4b9b-41b9-9e6b-d48798442425",
              "name": "Below Basic",
              "level": "Below Basic",
              "description": "The student made fewer than 3 citations"
            },
            {
              "id": "urn:uuid:c225be08-c67d-4ec8-ae8e-4860e83588ef",
              "name": "Basic",
              "level": "Basic",
              "description": "The student made 3-5 citations"
            },
            {
              "id": "urn:uuid:f256d3a9-c117-43bf-9e25-dc69691e18a1",
              "name": "Exceeds",
              "level": "Exceeds",
              "description": "The student made more than 5 citations"
            }
          ]
        }
      ]
    },
    "results": [
      {
        "resultDescription": "urn:uuid:da72e42e-9f38-4c42-83ac-33f6cb9bb3b1",
        "achievedLevel": "urn:uuid:f256d3a9-c117-43bf-9e25-dc69691e18a1"
      }
    ],
    "evidence": {
      "id": "https://example.org/my-robot-drones-analysis.html",
      "name": "My Robot Drones Analysis",
      "description": "A paper in APA format analyzing five different types of robot drones that look like birds.",
      "narrative": "This research paper compared different types of robot drones that are sometimes mistaken for birds and their impacts on the environment.",
      "genre": "Journal Article"
    }
  },
  "proof": {
    "type": "RsaSignature2018",
    "created": "2017-06-18T21:19:10Z",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:issuer#keys/1",
    "jws": "eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..TCYt5X"
  }
}`

**Comment by amiller-ims** [comment]
In the sample, the subject is identified by both `id` and `recipient` (an IdentityObject). If the `id` is clear text, why include `recipient`?

**Comment by kayaelle** [comment]
In this example both are available because the badge may have been issued originally to an email address but then the recipient may have added it to their wallet where it is associated with the DID. The email address provides the verifier with a second method to verify the recipient if needed. This scenario can be considered a bridge while badge issuers are still issuing to email addresses and DIDs are a new concept. It will likely be some time before organizations adopt DIDs and badges are issued directly to them. 

In 3.0 it could be that a badge is still only issued to the email address and not added to a VC wallet. 

A suggestion is to require either the credentialSubject.id or the recipient info and perhaps suggest that some verifiers would appreciate having both so that they can verify the DID and do a secondary validation for the email. 

In some instances, we may wish to add other information about the individual. Would it be more appropriate to use the profile object for that?

This is related to delegation & guardianship which is still being discussed at the VC level. Noting here for documentation purposes.

**Comment by amiller-ims** [comment]
If the subject adds an `id` (or anything) to the vc before sending it to a verifier, the issuer's proof will fail verification. The subject could add their `id` and re-issue the vc on their own, but the original issuer would be lost.

I do get your point that an issuer may want to include both `id` and `recipient` giving the verifier an option (or confirmation) that the subject is the person they think it is. The danger is that the `id` would then be tied to the hashed `identity` in the IdentityObject, Even if other issuer's only use `recipient`, nefarious verifiers would be able to connect the recipient to their `id`.

In [DIDs in Badges](https://github.com/IMSGlobal/openbadges-specification/blob/develop/ob_next/dids-in-badges.md), Gabe Cohen (and Nate I think) proposed adding `id` to the list of allowable properties to use when constructing the `recipient`. That was the reason the CLR project group added `id` to theirs.

Maybe `id` should NOT be allowed in the OpenBadges CredentialSubject, add `recipient`, and ALLOW `id` as one of the allowed hashed identifiers.

To help migration, `recipient` could be a set of IdentityObjects.

**Comment by kayaelle** [comment]
How the flow works is that the learner provides the DID to the issuer and then the issuer can include the DID as part of the credentialSubject and then it is signed. A learner can't add a DID after it was issued. The DID always originates either from the learner via their wallet or a pairwise DID that is agreed upon between the issuer and the learner. The latter hasn't been implemented in the wallets that are available now (as far as I know) but the former is a common API flow between wallets and issuing platforms. 

The reason issuers don't just create DIDs is that goes against self-sovereign identity principles of which verifiable credentials aim to meet. Learners should be able to decide what identity is associated with their credentials. This kind of happens now because learners tell issuers what their email addresses are and issuers can verify that. In the a similar way, wallets send the DID to the issuer and the issuer can verify that DID before deciding to issue to the learner.

Where we get into challenges is that learners aren't typically interacting with only the issuer when receiving their credentials. With most badging platforms the issuer is an organization using a platform. The issuer has verified the email address of the learner and provides that to the issuing platform. It's the issuing platform that interacts with the vc wallet and verifies the DID. If the DID and the email address are in the credentialSubject then the credential subject can be verified by both the DID and if the verifier chooses, the original email that the badge was issued to. What should happen in the future is that the issuer verifies the DID of the learner and then provides that DID to the platform so that when the learner connects their wallet to the platform the DIDs can be matched. DIDs aren't understood like email addresses and probably won't be for some time so a method of bridging and still giving the learner agency over their identity choice is to map the DID to the recipient email. 

We're working on writing up recommendations in VC-EDU and hope to tackle this in a meeting in a couple of weeks.

**Comment by kayaelle** [comment]
re: issuer and creator properties - I made a suggestion in #342 to align with CTDL CredentialOrganization

**Comment by amiller-ims** [comment]
Since the original issue (id or IdentityObject) was resolved with #351. And #342 is open for discussion, I am closing this issue.
