### ISSUE TITLE
Term collision: Evidence

### ISSUE THREAD

**Issue by amiller-ims** [IMSGlobal/openbadges-specification#344]
Both VC and OB define Evidence. This issue is to capture the discussion and decision for how to solve the collision.

VC: https://www.w3.org/TR/vc-data-model/#evidence
OB: https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#Evidence

Contexts

[VC v1](https://www.w3.org/2018/credentials/v1)

```
"cred": "https://www.w3.org/2018/credentials#",
"evidence": {
          "@id": "cred:evidence",
          "@type": "@id"
        }
```

[OB v2](https://openbadgespec.org/v2/context.json)

```
"obi": "https://w3id.org/openbadges#",
"Evidence": "obi:Evidence",
```

**Comment by amiller-ims** [comment]
Closing. I don't think there is a collision. They have different IRIs: `https://w3id.org/openbadges#evidence` versus `https://www.w3.org/2018/credentials#evidence`.

**Comment by kayaelle** [comment]
Based on our call today, I'd like to re-open this for discussion to make sure that the group is clear on the difference between the evidence in a badge and an evidence in a vc. They do have different IRIs and they do have different purposes:

- badge evidence (or in OBv3 - credentialSubject.evidence ) supports the achievement. It could be an array with one or more objects each containing an id that points to a url which contains the evidence for that specific achievement claim. That evidence could be a link to a photo, video, grades document, website on the badge issuing platform, etc. There may not be an id but instead a narrative containing content supporting the achievement claim.

- VC evidence provides the verifier additional methods to support the proof method if needed. For example, the verifier may request additional proof of identity such as a student id or government id to support the credentialSubject.DID. The VC evidence explains how to do that. The id may link to actual data - for instance if biometric data was being used, but the id could also link to information that explains the evidence that is being presented. For example, if the learner is presenting a. physical student id, the evidence id could link to a page that explains the traits of the physical id that make it valid. 

It's important that we make this distinction clear in support of the Open Badges community because VCs are new but OB evidence has been around for some time. As Andy notes, they do have different IRIs so having them both in the same credential could be possible but if we think it will be clearer for the community of issuers, learners, and verifiers, we could discuss calling the ob evidence, achievementEvidence or something along those lines.

**Comment by kayaelle** [comment]
My comment above is incorrect. The id in the vc.evidence is intended to link to data for the specific evidence for that specific VC not generically provide information about the evidence being presented. 

By learning this, it triggered some other thinking about credentialSubject.evidence and vc.evidence.  Will come back to this issue soon.

**Comment by amiller-ims** [comment]
I missed that vc `evidence` is not a property of the `credentialSubject`.

The descriptions and data models of vc `evidence` and ob `evidence` are compatible. We should probably raise ob `evidence` to the vc level.
