### ISSUE TITLE
Group Alignment on OpenBadgeCredential/AchievementCredential

### ISSUE THREAD

**Issue by justinpitcher** [IMSGlobal/openbadges-specification#381]

**Comment by danblickensderfer** [comment]
The OB 3.0 and CLR 2.0 work groups will need to discuss AchievementCredential naming for shared data model. We could add this to the agenda for CLR WG meeting on March 31. @danblickensderfer @amiller-ims

**Comment by danblickensderfer** [comment]
See https://github.com/IMSGlobal/openbadges-specification/pull/355

**Comment by amiller-ims** [comment]
Here is a little table that may help clarify the proposal

|   | OB 2.0 | OB 3.0 |
|--- |--- |--- |
| A single achievement assertion is called ___ in prose | a "badge" | a "badge" |
| The data model for an achievement assertion is named | "Assertion" | "AchievementCredential" |
| The JSON-LD term an achievement is | "badge" | "achievement" |
| The data model for an achievement is named | "BadgeClass" | "Achievement" |

**Comment by amiller-ims** [comment]
An argument against "AchievementCredential" is that it does not describe a skill assertion well (if a skill assertion does not have an achievement). One solution is to give skill assertions a different name like "SkillCredential".

An argument against "AssertionCredential" (IMO the most obvious migration to VC) is that--like "Assertion"--it is bland. The word "assertion" could be applied to any VC.

An argument against "OpenBadgesCredential" is that "Open Badges" is a strong brand with ingrained ideas about a badge is (an image, a micro-credential, ...). Folks in the CLR market have a hard time seeing their achievement assertions fitting the badge mold.

**Comment by amiller-ims** [comment]
Proposal:

- Rename JSON-LD @type from "Assertion" to "AssertionCredential"
- Add 3 aliases: "AchievementCredential", "OpenBadgeCredential", "SkillCredential"

**Comment by radhertz** [comment]
Does the proposal to create a SkillCredential imply that this is just claim of assertions and independent of any achievement per se.  That where an assertion of an achievement includes skills that would remain an AchievementCredential, with metadata within it consisting of various things, like a rubric, assessments, and if relevant skills?  

Another way to do this is leave skills out of the AchievementCredential entirely and where there are skills create a SkillCredential and hash link it that AchievementCredential.

**Comment by martyr280** [comment]
@radhertz correct, within the CLR model associations still exist that can relate a skillcredential to an achievement credential.

**Comment by radhertz** [comment]
@Marty - in that case wouldn't it be more parsimonious to simply leave out skills from the AchievementCredential metadata?  Let skills be a credential that can be associated with other types of credentials where appropriate.

**Comment by martyr280** [comment]
it's both/or

**Comment by radhertz** [comment]
It's probably best to separate the discussion about skills (as a separate credential, as a AchievementCredential with included skills metadata, etc. for its own issue.

**Comment by martyr280** [comment]
we have a CLR use case pending with a customer that would use this.

**Comment by martyr280** [comment]
but happy to have a separate issue.

**Comment by radhertz** [comment]
@martyr280  just for my late afternoon slowed cognition, your reference to a customer that "would like to use this"  - refers to which "this"?

**Comment by martyr280** [comment]
they would use SkillCredential

**Comment by ottonomy** [comment]
@andyfmiller the alias approach you propose seems to fit the bill to allow:
* CLR and OB implementers who resonate with the term "AchievementCredential" to use that term to describe the assertion
* CLR and OB implementers who resonate with the term "OpenBadgeCredential" to use that term to describe the assertion

I'm ok with that compromise. 

(I don't really see the need for `SkillCredential` and `AssertionCredential` to also appear in the mix. Looking forward to upcoming discussion of the use cases and example JSON for how to address those use cases for skill recognition. There could be a case made to use a different achievement type when you want to recognize a skill or a case made that all skill recognitions are that of some form of "achievement" even if it is not a "defined `Achievement` with criteria and an established assessment", but in neither case would we really need an *alias* for credential.type to cover the skills use case -- either it's the same type we use for other non-composite credentials under this spec or a different type)
--- 

One note on the history of the discussion: before we decided to try for that compromise, we didn't seem to put much effort into an approach where we advocated for the flexibility of a single term derived from the Open Badges community to describe this concept. You mentioned:
> "Open Badges" is a strong brand with ingrained ideas about what a badge is (an image, a micro-credential, ...)

That might be reputationally true, but it isn't technically true, and the few CLR planned implementers we've heard from on this issue didn't seem to be too keen on digging into that distinction or learning anew the range of many different things that "Open Badges" can represent: 
* micro-credentials or "macro" credentials
* competency-based recognition or recognition of things unrelated to skills or competencies
* participation recognition or rigorously assessed achievements
* academic achievements or social achievements... 

And in 3.0 in the proposal, it specifically calls out that we likely want to pursue use cases for which there is no image as a symbolic representation. Open Badges is a storied and respectable specification for an incredibly powerful and flexible concept. It has a long history and a vibrant community, and we can be proud to build upon that history as we make it even more flexible for the next generation of implementers. But there seems some resistance to using a technical name that makes it clear the scope of Achievement and Assertion arose from Open Badges and are at home within this spec that isn't actually grounded in technical capabilities or what implementers would need to present to users within their platforms. I'm not sure I understand this resistance other than that it might be a form of assumption that "badges" are only toys for children, which is something I would appreciate support form the whole community in pushing back against, because use cases for Open Badges run the exact same gamut as use cases for any other achievement use case that has arisen among CLR implementers. If we could have solved the issue that we are proposing to solve using an alias by just getting on the same page about the beautiful expressive range of possibilities that these data classes can represent, it's a shame that we end up complicating things and preserving an incorrect perception of badges as inflexibly tied to trivial use  cases or graphical symbolic representations of achievements.

**Comment by amiller-ims** [comment]
> but happy to have a separate issue.

There are two issues about skill assertions: #339 and #354

**Comment by amiller-ims** [comment]
> @andyfmiller the alias approach you propose seems to fit the bill to allow:

@ottonomy I was just the scribe, but I appreciate the feedback. @danblickensderfer and @martyr280 have included this topic the agenda for 3/31/2022.

**Comment by danblickensderfer** [comment]
See also (close one?) https://github.com/IMSGlobal/ComprehensiveLearnerRecord/issues/269

**Comment by amiller-ims** [comment]
Discussed in CLR project group meeting on 3/31. Decision: two terms: one in `obi:` namespace called `OpenBadgeCredential` and one alias called `AchievementCredential`. Both terms defined in OB 3.0 context file.

I'll make a PR.

**Comment by martyr280** [comment]
commented on #385 +1 to merge and close this issue.
