### ISSUE TITLE
is JSON-LD support mandatory ?

### ISSUE THREAD

**Issue by premgan** [IMSGlobal/openbadges-specification#447]
Per the spec “Though this specification requires that a @context property be present, it is not required that the value of the @context property be processed using JSON-LD. This is to support processing using plain JSON libraries, such as those that might be used when the verifiable credential is encoded as a JWT.” – So question: is JSON-LD support mandatory ?

**Comment by ottonomy** [comment]
From an issuer perspective, it is required for conformance to add the `@context` property in so that consumers may choose to perform JSON-LD processing on the data. This doesn't imply that the issuers or consumers of this data must perform JSON-LD-specific operations. This is a similar approach to how contexts are handled in the [Verifiable Credentials Data Model](https://w3c.github.io/vc-data-model/#contexts)

We're implementing VC. From the VC spec:
> [Verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credentials) and [verifiable presentations](https://w3c.github.io/vc-data-model/#dfn-verifiable-presentations) MUST include a @context [property](https://w3c.github.io/vc-data-model/#dfn-property).

**Comment by premgan** [comment]
https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#achievementcredential - Is there a reason then why this is the only context specified in the spec ?

<html>
<body>


Property | Type | Description | Multiplicity
-- | -- | -- | --
@context | URI | The value of the @context property MUST be an ordered set where the first item is a URI with the value 'https://www.w3.org/2018/credentials/v1', and the second item is a URI with the value '**https://purl.imsglobal.org/spec/ob/v3p0/context/ob_v3p0.jsonld**'. | [1..*]


</body>
</html>Property	Type	Description	Multiplicity
@context	[URI](https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#org.1edtech.ob.v3p0.derived.uri.class)	The value of the @context property MUST be an ordered set where the first item is a URI with the value 'https://www.w3.org/2018/credentials/v1', and the second item is a URI with the value 'https://purl.imsglobal.org/spec/ob/v3p0/context/ob_v3p0.jsonld'.	[1..*]
